#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

caddy_version="2.11.3"
caddy_hash="ee886eceda0ff9f30610d3be9b5b594026591e19add6b3961a341c72abe468e5eac9d7c2c2450bbb8420db1f827b954521f9336be4872f81090b8618adf8815a"
if [ "$TARGETARCH" == "arm64" ]; then
  caddy_hash="bd06996e1612cf5e9770dc7134313067ef3fdfde43b1a2196004906006de779372dcf7a0e7c7fb0890c23791179f12be4625f1b6e666a2abf37e8aff4c3a1826"
fi

task_working_dir
download "https://github.com/caddyserver/caddy/releases/download/v${caddy_version}/caddy_${caddy_version}_linux_${TARGETARCH}.tar.gz" "sha512" "$caddy_hash"
extract_download "caddy_${caddy_version}_linux_${TARGETARCH}.tar.gz"

install -D -m 755 "caddy" "$TEST_INSTALL_PREFIX/bin/caddy"

stamp
