#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

mailpit_version="1.30.0"
mailpit_hash="33c00f7633da7fc2f9c4ee490c7162fbb3586e97cfce6b2a66203168adb74b11"
if [ "$TARGETARCH" == "arm64" ]; then
  mailpit_hash="0d79af3dbe6792c66a030e4ed6abb885ef4ce3465b2daae0dbaa9859e780bd13"
fi

task_working_dir
download "https://github.com/axllent/mailpit/releases/download/v${mailpit_version}/mailpit-linux-${TARGETARCH}.tar.gz" "sha256" "$mailpit_hash"
extract_download "mailpit-linux-${TARGETARCH}.tar.gz"

install -D -m 755 "mailpit" "$TEST_INSTALL_PREFIX/bin/mailpit"

stamp
