#!/usr/bin/env bash


set -e -u -x
source ./tasks/helpers.sh

nodejs_version="22.22.3"
nodejs_hash="2e5d13569282d016861fae7c8f935e741693c269101a5bebcf761a5376d1f99f"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x64"
elif [ "$TARGETARCH" == "arm64" ]; then
  nodejs_hash="1c4a9933a5e45bc88f54f70b5f91232c127ec49f1a5989d23fb85824c7adf9b7"
fi

task_working_dir
download "https://nodejs.org/dist/v$nodejs_version/node-v$nodejs_version-linux-${download_arch}.tar.xz" "sha256" "$nodejs_hash"
extract_download "node-v$nodejs_version-linux-${download_arch}.tar.xz"

mkdir -p "$DEV_INSTALL_PREFIX"
rsync -a --itemize-changes "node-v$nodejs_version-linux-${download_arch}/" "$DEV_INSTALL_PREFIX/"

stamp
